apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentd-enterprise
resources:
  - regions.yaml
  - control-plane.yaml
  - worker-pools.yaml
  - network-policy.yaml
  - autoscaling.yaml
  - signed-images.yaml
configMapGenerator:
  - name: agentd-enterprise-policies
    files:
      - factory-load-model-v1.json=../../config/enterprise/factory-load-model-v1.json
      - retention-policy-v1.json=../../config/enterprise/retention-policy-v1.json
generatorOptions:
  disableNameSuffixHash: false
commonLabels:
  app.kubernetes.io/part-of: agentd-enterprise

